### PR TITLE
Upgrade to upstream version 1.15.0

### PR DESCRIPTION
**Pull request by Christophe31**
here a pull request to upgrade netdata to 1.15.0

It's made without special knowledge of the project so please review before accepting.

I updated the README.md using their up to date one.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Did you test this one on actual hardware? Did you test a new installation and updating an old one if that works flawlessly?

**Comment by Christophe31** [comment]
Nope, I thought YUnohost had a CI to do that and I didn't want to test it myself first on my server ^^. I wanted to see YUnohost CI results before hand.

**Comment by JimboJoe** [comment]
Hi @Christophe31 
Thanks for your contribution!
The only automatic CI for standard apps (not high quality/ex-official) is when there are published.
So developers/contributors need to test there code before publishing (which a universal good practice ;-).
If you don't have a development environment yet, you can have a look at [ynh-dev](https://github.com/YunoHost/ynh-dev) and [package_check](https://github.com/YunoHost/package_check). If you don't have any available hardware/virtual environment, you can also have a look at the [community development CI](https://forum.yunohost.org/t/proposition-for-a-new-non-official-ci/3595/5).

Anyway, I've pushed a commit to adapt configuration environment, that ought to be tested...

**Comment by Christophe31** [comment]
Thx!

**Pull request merged**
