### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by liberodark**
up to 1.11.0

### CODE REVIEW

**Comment by JimboJoe** [comment]
Hi again in the cyberworld!! :wink: 
Thanks for your PR.
For this to have a chance to work, you'll need to modify at least [app.src](https://github.com/YunoHost-Apps/netdata_ynh/blob/master/conf/app.src) and [README.md](https://github.com/YunoHost-Apps/netdata_ynh/blob/master/README.md).
I also advise you to test the result on a server and with [package_check](https://github.com/YunoHost/package_check).

**Comment by liberodark** [comment]
Have change all :D

**Comment by JimboJoe** [comment]
Hi, not sure you read my "EDIT" above: could you please make one unique consistent PR and test it?
Thanks!

**Comment by JimboJoe** [comment]
Closing as upgrade to 1.11.1 has been handled in #22

**Pull request closed without merging**
